from .student_grade_snapshot_collection import StudentGradeSnapshotListCreateView
from .student_grade_snapshot_detail import StudentGradeSnapshotDetailView

__all__ = ["StudentGradeSnapshotDetailView", "StudentGradeSnapshotListCreateView"]
