# Generated by Django 6.0.3 on 2026-08-10 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentgradesnapshot',
            name='unique_current_grade_per_student_term',
        ),
        migrations.AddField(
            model_name='studentgradesnapshot',
            name='enrollment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='grade_snapshots', to='academics.studentperiodenrollment'),
        ),
        migrations.AddConstraint(
            model_name='studentgradesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_grade', True)), fields=('enrollment',), name='unique_current_grade_per_enrollment'),
        ),
        migrations.RemoveField(
            model_name='studentgradesnapshot',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentgradesnapshot',
            name='term',
        ),
    ]
