# Generated by Django 6.0.3 on 2026-03-20 04:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('period_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'period_number'), name='unique_period')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('school_year', models.CharField(max_length=20)),
                ('semester', models.PositiveIntegerField(choices=[(1, 'First'), (2, 'Second')], default=1, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=2)])),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school_year', 'semester'), name='unique_term')],
            },
        ),
        migrations.CreateModel(
            name='StudentPeriodEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_enrollments', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period_enrollments', to='academics.term')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'period', 'term'), name='unique_student_period_term'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student', 'term'), name='unique_current_period_per_student_per_term')],
            },
        ),
    ]
